import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/store/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '데구르르',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko'>
      <body className={`${inter.className} cursor-default`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
